apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: unleash

resources:
  - namespace.yaml
  # secret.yaml — created dynamically by deploy script
  - configmap.yaml
  - deployment.yaml
  - service.yaml
  - istio-gateway.yaml
  - ingress.yaml
  - hpa.yaml
  - networkpolicy.yaml
